### ISSUE TITLE
STATUS_IMAGE_CERT_REVOKED returned with NtLoadDriver / CERT_E_REVOKED with StartService

### ISSUE THREAD

**Issue by shaygitub** [armvirus/CosMapper#2]
i needed to load an unsigned driver into memory when the system boots up, so i tried to integrate the script of mapping my unsigned driver inside a service with SERVICE_AUTO_START. when starting the service by request / when restarting the vm, when trying to load the driver of the mapper service into memory via NtLoadDriver (also tried with StartService), NtLoadDriver  returns status 0xC0000603 (STATUS_IMAGE_CERT_REVOKED) and StartService returns 0x800B010c (CERT_E_REVOKED). windows version is windows 10 home 22H2, os build 19045.3570 .
i also thought hat my integration mightve caused this problem so i tried the compiled CosUsermode program with my unsigned driver and NtLoadDriver also returned STATUS_IMAGE_CERT_REVOKED.
i will try to install 20H2 and see if its a version error but if there is some additional information that could be relevant, please respond to this issue / message on discord @ bldysis#0868, thanks!

**Comment by shaygitub** [comment]
20H2 also returns the same error code in the same call

**Comment by armvirus** [comment]
This issue is not related to the project.
